/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * A card transaction entry which will have a corresponding a financial transaction performed.
 */
@ApiModel(description = "A card transaction entry which will have a corresponding a financial transaction performed.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class CardTransaction {
    @SerializedName("encodedKey")
    private String encodedKey = null;

    @SerializedName("cardToken")
    private String cardToken = null;

    @SerializedName("externalReferenceId")
    private String externalReferenceId = null;

    @SerializedName("advice")
    private Boolean advice = false;

    @SerializedName("amount")
    private BigDecimal amount = null;

    @SerializedName("currencyCode")
    private String currencyCode = null;

    @SerializedName("cardAcceptor")
    private CardAcceptor cardAcceptor = null;

    @SerializedName("userTransactionTime")
    private String userTransactionTime = null;

    @SerializedName("externalAuthorizationReferenceId")
    private String externalAuthorizationReferenceId = null;

    /**
     * The encoded key of the entity, generated, globally unique
     *
     * @return encodedKey
     **/
    @ApiModelProperty(value = "The encoded key of the entity, generated, globally unique")
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * The reference token of the card.
     *
     * @return cardToken
     **/
    @ApiModelProperty(value = "The reference token of the card.")
    public String getCardToken() {
        return cardToken;
    }

    public CardTransaction externalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
        return this;
    }

    /**
     * The external reference ID to be used to reference the card transaction in subsequent requests.
     *
     * @return externalReferenceId
     **/
    @ApiModelProperty(required = true, value = "The external reference ID to be used to reference the card transaction in subsequent requests.")
    public String getExternalReferenceId() {
        return externalReferenceId;
    }

    public void setExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
    }

    public CardTransaction advice(Boolean advice) {
        this.advice = advice;
        return this;
    }

    /**
     * Whether the given request should be accepted without balance validations.
     *
     * @return advice
     **/
    @ApiModelProperty(required = true, value = "Whether the given request should be accepted without balance validations.")
    public Boolean isAdvice() {
        return advice;
    }

    public void setAdvice(Boolean advice) {
        this.advice = advice;
    }

    public CardTransaction amount(BigDecimal amount) {
        this.amount = amount;
        return this;
    }

    /**
     * The amount of money to be withdrawn in the financial transaction.
     *
     * @return amount
     **/
    @ApiModelProperty(required = true, value = "The amount of money to be withdrawn in the financial transaction.")
    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public CardTransaction currencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
        return this;
    }

    /**
     * The ISO currency code in which the card withdrawal reversal transaction is posted. The amounts are stored in the base currency, but the transaction can be created with a foreign currency.
     *
     * @return currencyCode
     **/
    @ApiModelProperty(value = "The ISO currency code in which the card withdrawal reversal transaction is posted. The amounts are stored in the base currency, but the transaction can be created with a foreign currency.")
    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public CardTransaction cardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
        return this;
    }

    /**
     * The card acceptor details.
     *
     * @return cardAcceptor
     **/
    @ApiModelProperty(value = "The card acceptor details.")
    public CardAcceptor getCardAcceptor() {
        return cardAcceptor;
    }

    public void setCardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
    }

    public CardTransaction userTransactionTime(String userTransactionTime) {
        this.userTransactionTime = userTransactionTime;
        return this;
    }

    /**
     * The formatted time at which the user made this card transaction.
     *
     * @return userTransactionTime
     **/
    @ApiModelProperty(value = "The formatted time at which the user made this card transaction.")
    public String getUserTransactionTime() {
        return userTransactionTime;
    }

    public void setUserTransactionTime(String userTransactionTime) {
        this.userTransactionTime = userTransactionTime;
    }

    public CardTransaction externalAuthorizationReferenceId(String externalAuthorizationReferenceId) {
        this.externalAuthorizationReferenceId = externalAuthorizationReferenceId;
        return this;
    }

    /**
     * The external authorization hold reference ID, which relates this card transaction to a previous authorization hold.
     *
     * @return externalAuthorizationReferenceId
     **/
    @ApiModelProperty(value = "The external authorization hold reference ID, which relates this card transaction to a previous authorization hold.")
    public String getExternalAuthorizationReferenceId() {
        return externalAuthorizationReferenceId;
    }

    public void setExternalAuthorizationReferenceId(String externalAuthorizationReferenceId) {
        this.externalAuthorizationReferenceId = externalAuthorizationReferenceId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CardTransaction cardTransaction = (CardTransaction) o;
        return Objects.equals(this.encodedKey, cardTransaction.encodedKey) &&
                Objects.equals(this.cardToken, cardTransaction.cardToken) &&
                Objects.equals(this.externalReferenceId, cardTransaction.externalReferenceId) &&
                Objects.equals(this.advice, cardTransaction.advice) &&
                Objects.equals(this.amount, cardTransaction.amount) &&
                Objects.equals(this.currencyCode, cardTransaction.currencyCode) &&
                Objects.equals(this.cardAcceptor, cardTransaction.cardAcceptor) &&
                Objects.equals(this.userTransactionTime, cardTransaction.userTransactionTime) &&
                Objects.equals(this.externalAuthorizationReferenceId, cardTransaction.externalAuthorizationReferenceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(encodedKey, cardToken, externalReferenceId, advice, amount, currencyCode, cardAcceptor, userTransactionTime, externalAuthorizationReferenceId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CardTransaction {\n");

        sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
        sb.append("    cardToken: ").append(toIndentedString(cardToken)).append("\n");
        sb.append("    externalReferenceId: ").append(toIndentedString(externalReferenceId)).append("\n");
        sb.append("    advice: ").append(toIndentedString(advice)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
        sb.append("    cardAcceptor: ").append(toIndentedString(cardAcceptor)).append("\n");
        sb.append("    userTransactionTime: ").append(toIndentedString(userTransactionTime)).append("\n");
        sb.append("    externalAuthorizationReferenceId: ").append(toIndentedString(externalAuthorizationReferenceId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

