/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Holds the deposit overdraft interest settings
 */
@ApiModel(description = "Holds the deposit overdraft interest settings")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class DepositOverdraftInterestSettings {
    @SerializedName("interestRate")
    private BigDecimal interestRate = null;

    @SerializedName("indexInterestRate")
    private BigDecimal indexInterestRate = null;

    public DepositOverdraftInterestSettings interestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
        return this;
    }

    /**
     * The interest rate that was set or changed in this transaction. Used on product interest rate changes or interest tier switches
     *
     * @return interestRate
     **/
    @ApiModelProperty(value = "The interest rate that was set or changed in this transaction. Used on product interest rate changes or interest tier switches")
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    public DepositOverdraftInterestSettings indexInterestRate(BigDecimal indexInterestRate) {
        this.indexInterestRate = indexInterestRate;
        return this;
    }

    /**
     * The value of the index interest rate set or changed in this transaction
     *
     * @return indexInterestRate
     **/
    @ApiModelProperty(value = "The value of the index interest rate set or changed in this transaction")
    public BigDecimal getIndexInterestRate() {
        return indexInterestRate;
    }

    public void setIndexInterestRate(BigDecimal indexInterestRate) {
        this.indexInterestRate = indexInterestRate;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositOverdraftInterestSettings depositOverdraftInterestSettings = (DepositOverdraftInterestSettings) o;
        return Objects.equals(this.interestRate, depositOverdraftInterestSettings.interestRate) &&
                Objects.equals(this.indexInterestRate, depositOverdraftInterestSettings.indexInterestRate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(interestRate, indexInterestRate);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositOverdraftInterestSettings {\n");

        sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
        sb.append("    indexInterestRate: ").append(toIndentedString(indexInterestRate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

