/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Holds the deposit overdraft settings for a transaction
 */
@ApiModel(description = "Holds the deposit overdraft settings for a transaction")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class DepositOverdraftSettings {
    @SerializedName("overdraftLimit")
    private BigDecimal overdraftLimit = null;

    public DepositOverdraftSettings overdraftLimit(BigDecimal overdraftLimit) {
        this.overdraftLimit = overdraftLimit;
        return this;
    }

    /**
     * The overdraft limit that was set or changed in this transaction
     *
     * @return overdraftLimit
     **/
    @ApiModelProperty(value = "The overdraft limit that was set or changed in this transaction")
    public BigDecimal getOverdraftLimit() {
        return overdraftLimit;
    }

    public void setOverdraftLimit(BigDecimal overdraftLimit) {
        this.overdraftLimit = overdraftLimit;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositOverdraftSettings depositOverdraftSettings = (DepositOverdraftSettings) o;
        return Objects.equals(this.overdraftLimit, depositOverdraftSettings.overdraftLimit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(overdraftLimit);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositOverdraftSettings {\n");

        sb.append("    overdraftLimit: ").append(toIndentedString(overdraftLimit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

