/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * The interest settings, holds all the properties regarding interests for the deposit account
 */
@ApiModel(description = "The interest settings, holds all the properties regarding interests for the deposit account")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class DepositTransactionInterestSettings {
    @SerializedName("interestRate")
    private BigDecimal interestRate = null;

    public DepositTransactionInterestSettings interestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
        return this;
    }

    /**
     * The interest rate for the deposit account
     *
     * @return interestRate
     **/
    @ApiModelProperty(value = "The interest rate for the deposit account")
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositTransactionInterestSettings depositTransactionInterestSettings = (DepositTransactionInterestSettings) o;
        return Objects.equals(this.interestRate, depositTransactionInterestSettings.interestRate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(interestRate);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositTransactionInterestSettings {\n");

        sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

