/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Represents the request payload for creating a transaction of type FEE_APPLIED.
 */
@ApiModel(description = "Represents the request payload for creating a transaction of type FEE_APPLIED.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class FeeAppliedDepositTransactionInput {
    @SerializedName("externalId")
    private String externalId = null;

    @SerializedName("predefinedFeeKey")
    private String predefinedFeeKey = null;

    @SerializedName("amount")
    private BigDecimal amount = null;

    @SerializedName("notes")
    private String notes = null;

    public FeeAppliedDepositTransactionInput externalId(String externalId) {
        this.externalId = externalId;
        return this;
    }

    /**
     * The external id of the current transaction, customizable, unique
     *
     * @return externalId
     **/
    @ApiModelProperty(value = "The external id of the current transaction, customizable, unique")
    public String getExternalId() {
        return externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    public FeeAppliedDepositTransactionInput predefinedFeeKey(String predefinedFeeKey) {
        this.predefinedFeeKey = predefinedFeeKey;
        return this;
    }

    /**
     * The encodedKey of the predefined fee that defines the current fee
     *
     * @return predefinedFeeKey
     **/
    @ApiModelProperty(value = "The encodedKey of the predefined fee that defines the current fee")
    public String getPredefinedFeeKey() {
        return predefinedFeeKey;
    }

    public void setPredefinedFeeKey(String predefinedFeeKey) {
        this.predefinedFeeKey = predefinedFeeKey;
    }

    public FeeAppliedDepositTransactionInput amount(BigDecimal amount) {
        this.amount = amount;
        return this;
    }

    /**
     * The value of the fee applied on the account
     *
     * @return amount
     **/
    @ApiModelProperty(value = "The value of the fee applied on the account")
    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public FeeAppliedDepositTransactionInput notes(String notes) {
        this.notes = notes;
        return this;
    }

    /**
     * Extra notes about the current transaction
     *
     * @return notes
     **/
    @ApiModelProperty(value = "Extra notes about the current transaction")
    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FeeAppliedDepositTransactionInput feeAppliedDepositTransactionInput = (FeeAppliedDepositTransactionInput) o;
        return Objects.equals(this.externalId, feeAppliedDepositTransactionInput.externalId) &&
                Objects.equals(this.predefinedFeeKey, feeAppliedDepositTransactionInput.predefinedFeeKey) &&
                Objects.equals(this.amount, feeAppliedDepositTransactionInput.amount) &&
                Objects.equals(this.notes, feeAppliedDepositTransactionInput.notes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(externalId, predefinedFeeKey, amount, notes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FeeAppliedDepositTransactionInput {\n");

        sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
        sb.append("    predefinedFeeKey: ").append(toIndentedString(predefinedFeeKey)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

