/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Contains the details about transaction including fields like transaction channel key and channel ID
 */
@ApiModel(description = "Contains the details about transaction including fields like transaction channel key and channel ID")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class TransactionDetailsInput {
    @SerializedName("transactionChannelKey")
    private String transactionChannelKey = null;

    @SerializedName("transactionChannelId")
    private String transactionChannelId = null;

    public TransactionDetailsInput transactionChannelKey(String transactionChannelKey) {
        this.transactionChannelKey = transactionChannelKey;
        return this;
    }

    /**
     * The encoded key of the transaction channel associated with the transaction details.
     *
     * @return transactionChannelKey
     **/
    @ApiModelProperty(value = "The encoded key of the transaction channel associated with the transaction details.")
    public String getTransactionChannelKey() {
        return transactionChannelKey;
    }

    public void setTransactionChannelKey(String transactionChannelKey) {
        this.transactionChannelKey = transactionChannelKey;
    }

    public TransactionDetailsInput transactionChannelId(String transactionChannelId) {
        this.transactionChannelId = transactionChannelId;
        return this;
    }

    /**
     * The id of the transaction channel associated with the transaction details.
     *
     * @return transactionChannelId
     **/
    @ApiModelProperty(value = "The id of the transaction channel associated with the transaction details.")
    public String getTransactionChannelId() {
        return transactionChannelId;
    }

    public void setTransactionChannelId(String transactionChannelId) {
        this.transactionChannelId = transactionChannelId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransactionDetailsInput transactionDetailsInput = (TransactionDetailsInput) o;
        return Objects.equals(this.transactionChannelKey, transactionDetailsInput.transactionChannelKey) &&
                Objects.equals(this.transactionChannelId, transactionDetailsInput.transactionChannelId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transactionChannelKey, transactionChannelId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TransactionDetailsInput {\n");

        sb.append("    transactionChannelKey: ").append(toIndentedString(transactionChannelKey)).append("\n");
        sb.append("    transactionChannelId: ").append(toIndentedString(transactionChannelId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

