/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Represents the transfer details, such as the linked transaction key
 */
@ApiModel(description = "Represents the transfer details, such as the linked transaction key")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-16T09:34:36.124Z")
public class TransferDetails {
    @SerializedName("linkedLoanTransactionKey")
    private String linkedLoanTransactionKey = null;

    @SerializedName("linkedDepositTransactionKey")
    private String linkedDepositTransactionKey = null;

    public TransferDetails linkedLoanTransactionKey(String linkedLoanTransactionKey) {
        this.linkedLoanTransactionKey = linkedLoanTransactionKey;
        return this;
    }

    /**
     * The key of the related loan transaction
     *
     * @return linkedLoanTransactionKey
     **/
    @ApiModelProperty(value = "The key of the related loan transaction")
    public String getLinkedLoanTransactionKey() {
        return linkedLoanTransactionKey;
    }

    public void setLinkedLoanTransactionKey(String linkedLoanTransactionKey) {
        this.linkedLoanTransactionKey = linkedLoanTransactionKey;
    }

    public TransferDetails linkedDepositTransactionKey(String linkedDepositTransactionKey) {
        this.linkedDepositTransactionKey = linkedDepositTransactionKey;
        return this;
    }

    /**
     * The key of the related deposit transaction
     *
     * @return linkedDepositTransactionKey
     **/
    @ApiModelProperty(value = "The key of the related deposit transaction")
    public String getLinkedDepositTransactionKey() {
        return linkedDepositTransactionKey;
    }

    public void setLinkedDepositTransactionKey(String linkedDepositTransactionKey) {
        this.linkedDepositTransactionKey = linkedDepositTransactionKey;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransferDetails transferDetails = (TransferDetails) o;
        return Objects.equals(this.linkedLoanTransactionKey, transferDetails.linkedLoanTransactionKey) &&
                Objects.equals(this.linkedDepositTransactionKey, transferDetails.linkedDepositTransactionKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(linkedLoanTransactionKey, linkedDepositTransactionKey);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TransferDetails {\n");

        sb.append("    linkedLoanTransactionKey: ").append(toIndentedString(linkedLoanTransactionKey)).append("\n");
        sb.append("    linkedDepositTransactionKey: ").append(toIndentedString(linkedDepositTransactionKey)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

